### ISSUE TITLE
Three changes compared to keras version v1

### ISSUE THREAD

**Issue by rainsun1** [foamliu/Deep-Image-Matting-v2#14]
I noticed 3 insteresting changes in this version compared to v1:
1. "compositional_loss" and "overall_loss" are removed, and only "alpha_prediction_loss" remains.
2. "model refinement" step with dense layers or "torch.nn.linear" are removed, and only "encorder and decoder" layers remains.
So, maybe this is a light version of v1.
3. "generate_trimap(alpha)" function changes a lot, which can generate much large and usual unknown region size and is perhaps a key point for the improvement of the results.

**Comment by foamliu** [comment]
Thanks for the good summary.
