### ISSUE TITLE
pretrained tar archive is broken?

### ISSUE THREAD

**Issue by eps696** [foamliu/Deep-Image-Matting-v2#15]
i've downloaded the [model](https://github.com/foamliu/Deep-Image-Matting-v2/releases/download/v1.0/BEST_checkpoint.tar) but both 7z and tar reports unknown format.

any suggestions what to check? 
i'm on windows, if it matters

**Comment by madhukirand** [comment]
you don't have to unzip the tarfile for loading weights, "torch.load" loads weights from tarfile itself.
like
```
checkpoint = 'BEST_checkpoint.tar'
checkpoint = torch.load(checkpoint,map_location='cpu')
model = checkpoint['model'].module
model = model.to(device)
```

**Comment by foamliu** [comment]
Thanks @madhukirand.
