### ISSUE TITLE
How to get this dirs? I can't find These imgs.

### ISSUE THREAD

**Issue by coolmian** [foamliu/Deep-Image-Matting-v2#16]
fg_path_test = 'data/fg_test/'
a_path_test = 'data/mask_test/'
bg_path_test = 'data/bg_test/'

**Comment by FUNGERN** [comment]
These photo data need to contact Adobe

**Comment by coolmian** [comment]
> These photo data need to contact Adobe
Thanks, I got in touch

**Comment by leijue222** [comment]
If I don't have an Adobe dataset, can I run a certain file of the project? 
E.g. demo.py or test.py
