### ISSUE TITLE
Deep-Image-Matting-v2 implemetation on Android

### ISSUE THREAD

**Issue by charlizesmith** [foamliu/Deep-Image-Matting-v2#18]
Hi,
Thanks for you work!
its looking awesome output.
I want to integrate your demo into android project. Is it possible to integrate model into android Project? If it possible, then How can i integrate this model into android project?
Can you please give some suggestions?
Thanks in advance.

**Comment by InternetMaster1** [comment]
Any help?

**Comment by austingg** [comment]
you may convert the pytorch model to onnx, then convert to ncnn model. you can use ncnn for inference on Android device eventually

**Comment by foamliu** [comment]
This is sth. you want: https://pytorch.org/mobile/home/.
