### ISSUE TITLE
the frozen model named BEST_checkpoint.tar cannot be uncompressed 

### ISSUE THREAD

**Issue by banrenmasanxing** [foamliu/Deep-Image-Matting-v2#19]
when I try to uncompress the frozen model
it shows 

tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors

this means the .tar file is not complete

**Comment by FUNGERN** [comment]
No artificial decompression required, he is intact

**Comment by Ricelll** [comment]
You can think of it as a way of naming.
I think ".tar"  like ".pth".

**Comment by foamliu** [comment]
Thanks. @FUNGERN and @Ricelll are right.

**Comment by leijue222** [comment]
I can't find the file of BEST_checkpoint.tar.
Could you tell me where can I find it?

**Comment by Ricelll** [comment]
> I can't find the file of BEST_checkpoint.tar.
> Could you tell me where can I find it?

@leijue222
![link](https://user-images.githubusercontent.com/31204531/72048160-222e6c00-32f7-11ea-8b30-7a0b3648ca03.png)
this link.

**Comment by leijue222** [comment]
> > I can't find the file of BEST_checkpoint.tar.
> > Could you tell me where can I find it?
> 
> @leijue222
> ![link](https://user-images.githubusercontent.com/31204531/72048160-222e6c00-32f7-11ea-8b30-7a0b3648ca03.png)
> this link.
Thanks!
