### ISSUE TITLE
The pretrained model not found

### ISSUE THREAD

**Issue by MarSaKi** [foamliu/Deep-Image-Matting-v2#2]
The pretrainde model not found , could you commit it again?

**Comment by rjadr** [comment]
It can be found [here](https://github.com/foamliu/Deep-Image-Matting/releases).

**Comment by MarSaKi** [comment]
> It can be found [here](https://github.com/foamliu/Deep-Image-Matting/releases).



> It can be found [here](https://github.com/foamliu/Deep-Image-Matting/releases).

I'm sorry , but this link is for v1 model , I want v2 model using pytorch?

**Comment by foamliu** [comment]
Thanks @MarSaKi for kind reminder, uploaded.
