### ISSUE TITLE
Question about  data(alpha or trimp)

### ISSUE THREAD

**Issue by leijue222** [foamliu/Deep-Image-Matting-v2#24]
Thank you very much for making this project open source. I have a question and I hope to get your answer.

In the demo.py
We should provide two images:
1. image(put in data/fg_test),I temporarily call it 1.png
2. imges's alpha (put in data/mask_test),I temporarily call it 1_alpha.png

Does 1_alpha.png must be obtained manually by PS？
Is there any way to get it automatically？
So we only need to upload a picture of 1.png.

**Comment by foamliu** [comment]
Yes, trimap is necessary in this settings.
