### ISSUE TITLE
File not Found error Adobe_Deep_Image_Matting_Dataset even though i have the dataset in the Data folder

### ISSUE THREAD

**Issue by yeshwanth28** [foamliu/Deep-Image-Matting-v2#25]
I have the dataset in the data folder unextracted with the same name. Though it displays file not found error while I try to run pre_process.py

**Comment by yeshwanth28** [comment]
![image](https://user-images.githubusercontent.com/50314132/74624147-59e9c880-516d-11ea-9648-502cc7720e51.png)

**Comment by huangjunxiong11** [comment]
You need more than one file.Actually,you need four documents.
train2014.zip
VOC2008test.tar
VOCtrainval_14-Jul-2008.tar
and
Adobe_Deep_Matting_Dataset.zip
You have to download them first

Good luck

**Comment by foamliu** [comment]
Thanks @huangjunxiong11 , clear and concise.
