### ISSUE TITLE
'train_names.txt'   what it is?

### ISSUE THREAD

**Issue by huangjunxiong11** [foamliu/Deep-Image-Matting-v2#26]
After i run pre_process.py successfully, i run train.py but failed. The error shows me that 'FileNotFoundError: [Errno 2] No such file or directory: 'train_names.txt''. i have no this file. What's worse, i do not know anything about this file 'train_names.txt'. What should i do?

**Comment by huangjunxiong11** [comment]
After runing data_gen.py , you can get that

**Comment by foamliu** [comment]
Right.
