### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by huangjunxiong11** [foamliu/Deep-Image-Matting-v2#27]
When i run train.py, I get this error "RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED", What made this error? What should I do? The configuration environment of my computer is ‘python3.5 pytorch1.1.0 cudn9.0 cudnn7.1.3 torchvision0.3.0’

**Comment by foamliu** [comment]
Seems an environment issue. Please make sure the environment setup (pytorch, cuda, cudnn) is right.

**Comment by foamliu** [comment]
Especially cuda and cudnn versions are compatiable.
