### ISSUE TITLE
can not unpack the 'BEST_checkpoint.tar'

### ISSUE THREAD

**Issue by huangjunxiong11** [foamliu/Deep-Image-Matting-v2#28]
When i download the file "BEST_checkpoint.tar" successfully, i can't unpack it. Actually, when i try to unpack 'BEST_checkpoint.tar', it make an error. Is it my fault , or, Is the file mistaken?

**Comment by wqs111000** [comment]
I also faced this problem.

**Comment by wqs111000** [comment]
I hope the author or anyone else can send a copy of 'BEST_checkpoint.tar' without errors to my email( wqs_zju@163.com).Thanks a lot.

**Comment by foamliu** [comment]
This is actually a .pth file, you don't need to unpack it.
