### ISSUE TITLE
v2 didn't performance well as v1? 

### ISSUE THREAD

**Issue by MarSaKi** [foamliu/Deep-Image-Matting-v2#3]
Hi,
thanks for your pretrained model!
I test both your v1 pretrained model and v2 pretrained model , v2 is much faster than v1 , but I found it didn't performance well as v1.
the image:
![WechatIMG226](https://user-images.githubusercontent.com/24617881/61368368-48330080-a8c0-11e9-84e7-deecaefb41f9.jpeg)
the origin tri map:
![test7_tri](https://user-images.githubusercontent.com/24617881/61368220-fbe7c080-a8bf-11e9-8bf6-65d3cfc3b4ac.png)
the v1 output:
![WechatIMG225](https://user-images.githubusercontent.com/24617881/61368312-2b96c880-a8c0-11e9-9db5-7a8e07b3336f.jpeg)
the v2 output:
![test7_result](https://user-images.githubusercontent.com/24617881/61368329-35b8c700-a8c0-11e9-974e-e53297091ea7.png)

do you know what's the problem?

Thanks,

**Comment by foamliu** [comment]
Fix a bug, please try again.

**Comment by foamliu** [comment]
Please feel free to re-open this issue if it reproduce.

**Comment by Thunder003** [comment]
Hi @foamliu, what changes did you u made for fixing that problem? I'm also getting results like @MarSaKi.

I'm trying to train it on my custom dataset but the results are not coming well. Even not like the pre-trained you have shared.
