### ISSUE TITLE
How can i get the Trimaps of my pictures?

### ISSUE THREAD

**Issue by huangjunxiong11** [foamliu/Deep-Image-Matting-v2#31]
Now,  I got a model, I want to use it but I can't, because I have not the Trimaps of my pictures. Are  there the script of code to build the Trimaps?  How can i get the Trimaps of my pictures?

**Comment by leijue222** [comment]
The principle of the paper requires us to provide two pictures：images and the image's trimap
![1585115954(1)](https://user-images.githubusercontent.com/30276789/77506735-83e78680-6ea1-11ea-9ee3-b463e0924b47.jpg)

Get Trimap's code in here:
https://github.com/foamliu/Deep-Image-Matting-PyTorch/blob/db6a96de7dd28e0a6746ec4d9a1c2efdf200c701/data_gen.py#L87

But this function need we provide alpha image.
It seems we have to get it by ourself.
Obtained manually by PS or by semantic segmentation model

This is my personal view,I don't know if this is right.

**Comment by sunweixings** [comment]
你好，请问你是否能提供预训练模型以供参考？

**Comment by foamliu** [comment]
It depends on trimaps.
