### ISSUE TITLE
run demo.py question！

### ISSUE THREAD

**Issue by kxcg99** [foamliu/Deep-Image-Matting-v2#32]
File "demo.py", line 84, in <module>
    new_bgs = random.sample(new_bgs, 10)
  File "C:\Users\15432\AppData\Local\conda\conda\envs\python34\lib\random.py", line 324, in sample
    raise ValueError("Sample larger than population")
ValueError: Sample larger than population

**Comment by sunweixings** [comment]
你好，请问你能否提供训练模型以供参考？

**Comment by sunweixings** [comment]
hello，can you provide the pretrained  model？

**Comment by sunweixings** [comment]
sorry，I found the pre-trained model the author provide is destroyed.So can you send me?

**Comment by syoung125** [comment]
I have same problem

**Comment by foamliu** [comment]
Need to prepare the background images.
