### ISSUE TITLE
Invalid BEST_checkpoint.tar ?

### ISSUE THREAD

**Issue by flocreate** [foamliu/Deep-Image-Matting-v2#37]
Hi, thank you for the code.
I tried to download the pretrained model and extract it but it dosnt work.
```
tar xvf BEST_checkpoint.tar BEST_checkpoint
```
results in 
```
tar: Ceci ne ressemble pas à une archive de type « tar »
tar: On saute à l'en-tête suivant
tar: BEST_checkpoint : non trouvé dans l'archive
tar: Arrêt avec code d'échec à cause des erreurs précédentes
```

anything i'm doing the wrong way ? or the provided tar is not valid ?
kind reards

**Comment by lisonnnnnnnn** [comment]
+1

**Comment by kashyappiyush1998** [comment]
In windows this shows Invalid or damaged on exteaction

**Comment by jackytu256** [comment]
same as me

**Comment by kritiksoman** [comment]
same

**Comment by foamliu** [comment]
It is not "TAR" format, please refer to the demo.py file for reading it.
