### ISSUE TITLE
my own datasets are all full human body images

### ISSUE THREAD

**Issue by lfxx** [foamliu/Deep-Image-Matting-v2#38]
Hi,thanks for your excellent work.Now i prepare my own datasets.This datasets are consists of thounds of high resolution image(average 4000*4000).They are all full  human body images.When i 
 process these images,i meet a questions:
When i crop the trimap(generated from alpha),often crop some places which are not include hair.Such as foot,leg.Is it ok to input these images into model?@foamliu

**Comment by lfxx** [comment]
> Hi,thanks for your excellent work.Now i prepare my own datasets.This datasets are consists of thounds of high resolution image(average 4000*4000).They are all full human body images.When i
> process these images,i meet a questions:
> When i crop the trimap(generated from alpha),often crop some places which are not include hair.Such as foot,leg.Is it ok to input these images into model?@foamliu

i tried to train the model using those samples,find that model hard to converage.In my opinion,the images inputted to model must include hair.Am i right?

**Comment by polly-morphism** [comment]
> > Hi,thanks for your excellent work.Now i prepare my own datasets.This datasets are consists of thounds of high resolution image(average 4000*4000).They are all full human body images.When i
> > process these images,i meet a questions:
> > When i crop the trimap(generated from alpha),often crop some places which are not include hair.Such as foot,leg.Is it ok to input these images into model?@foamliu
> 
> i tried to train the model using those samples,find that model hard to converage.In my opinion,the images inputted to model must include hair.Am i right?

Hi. I have a similar dataset (2k full body images with masks 2.5k*3k pixels). Were you able to successfully train the model? I don't have hair in my dataset at all. How long did it take to train the model? What GPU did you use? I will be so grateful for any information)

**Comment by xiankgx** [comment]
These CNN models are usually not trained on full sized images. For 2k images, and around 50 epochs, training will probably only take a few hours on a GPU.

**Comment by xiankgx** [comment]
If you don't mind, can you share your dataset?

**Comment by foamliu** [comment]
The model is highly dependent on trimaps.
