### ISSUE TITLE
unable to start training using pretrained weigths

### ISSUE THREAD

**Issue by ghost** [foamliu/Deep-Image-Matting-v2#4]
whenever pre-trained weights are used for training the model using own dataset, the following error is occurring.

python3 train.py --batch-size 4 --checkpoint checkpoint/BEST_checkpoint.tar 

/usr/local/lib/python3.5/dist-packages/torch/serialization.py:454: SourceChangeWarning: source code of class 'torch.nn.parallel.data_parallel.DataParallel' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/lib/python3.5/dist-packages/torch/serialization.py:454: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/lib/python3.5/dist-packages/torch/serialization.py:454: SourceChangeWarning: source code of class 'torch.nn.modules.batchnorm.BatchNorm2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/lib/python3.5/dist-packages/torch/serialization.py:454: SourceChangeWarning: source code of class 'torch.nn.modules.activation.ReLU' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
Traceback (most recent call last):
  File "train.py", line 180, in <module>
    main()
  File "train.py", line 176, in main
    train_net(args)
  File "train.py", line 71, in train_net
    logger=logger)
  File "train.py", line 112, in train
    alpha_out = model(img)  # [N, 3, 320, 320]
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/parallel/data_parallel.py", line 143, in forward
    if t.device != self.src_device_obj:
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 539, in __getattr__
    type(self).__name__, name))
AttributeError: 'DataParallel' object has no attribute 'src_device_obj'

**Comment by foamliu** [comment]
Are you using GPU?

**Comment by foamliu** [comment]
Fixed, feel free to activate this if it repro.

**Comment by ghost** [comment]
@foamliu yes, I'm using a GPU.
