### ISSUE TITLE
result is not good, why?

### ISSUE THREAD

**Issue by pxEkin** [foamliu/Deep-Image-Matting-v2#42]
python demo.py, and get follow results, i don't know why result is not good:
![0_compose](https://user-images.githubusercontent.com/40013733/89868713-da055e00-dbe5-11ea-8e25-364c5ceb452b.png)
![1_compose](https://user-images.githubusercontent.com/40013733/89868735-e25d9900-dbe5-11ea-8a25-92f0a2f3a887.png)
![0_trimap](https://user-images.githubusercontent.com/40013733/89868856-0f11b080-dbe6-11ea-9006-b4b1268287a0.png)
![1_out](https://user-images.githubusercontent.com/40013733/89868891-1c2e9f80-dbe6-11ea-8c25-96387800f761.png)

**Comment by KevorkSulahian** [comment]
yeah i was trying to use my own pictures to test and honestly it was horrible a simple grabcut was much better than this

**Comment by foamliu** [comment]
I don't know.
