### ISSUE TITLE
evaluate problem

### ISSUE THREAD

**Issue by D0ub1ePieR** [foamliu/Deep-Image-Matting-v2#46]
Is the evaluation progress like
    input 1920 * 1080 alpha 1920 * 1080 trimap 1920 *1080
then resize input and trimap to 320 * 320
    input 320 * 320 trimap 320 * 320 to the model, then get the prediction 320 * 320
prediction 320 * 320, resize to 1920 * 1080
    pred 1920 * 1080 alpha 1920 * 1080
finally compare the resized prediction and the alpha(gt)
***************
i test on the DIM-tensorflow version and cannot get the number in paper, because the sad,mse,conn and grad are effected by the image size
Thanks

**Comment by foamliu** [comment]
Please take a look at this script -- eval.py, you don't need to resize, the network can be adapted to different sizes.
