### ISSUE TITLE
About the number of training fgs in Adobe dataset?

### ISSUE THREAD

**Issue by Serge-weihao** [foamliu/Deep-Image-Matting-v2#48]
![image](https://user-images.githubusercontent.com/40890323/103440073-b10d6480-4c7d-11eb-8388-6c3dde47a6bb.png)

they wrote that there are 493 fgs in their paper,
![image](https://user-images.githubusercontent.com/40890323/103440095-d306e700-4c7d-11eb-87da-80ac8561fe15.png)

but they said taht there are 455 fgs on their webpage.
And your file shows that there are only 431 training fgs.
Could you explain these problems?

**Comment by foamliu** [comment]
I remember some training images were not shared due to some kind of legal restriction.
