### ISSUE TITLE
怎么提取前景呢

### ISSUE THREAD

**Issue by albertyou2** [foamliu/Deep-Image-Matting-v2#49]
您好好@foamliu： 
MATTING效果非常棒！

我的任务是吧前景提取出来，
我想问下，如何通过您的这个MATTING库提取出前景图像呢？我想应该比较简单，但我对matting不是很了解所以不太会
能否做一个简单的说明，非常感谢！

**Comment by foamliu** [comment]
This is a general matting project, for this you still need trimap. I think what you need is a specific tool to extract certain foreground (e.g. person).
