### ISSUE TITLE
about the result

### ISSUE THREAD

**Issue by wrrJasmine** [foamliu/Deep-Image-Matting-v2#7]
Thanks for your great work!
I saw your result is much better than the paper post. Is the fc6 you dropped matters?

**Comment by wrrJasmine** [comment]
I replaced the trimaps generated by the function gen_trimap in util.py by the trimaps DIM author provided, the sad is 66,and the mse is 0.023. I konw the trimap matters to the test results . I am wonder that if I want to compare the result with DIM,  I should use the trimaps author  provided, right?

**Comment by wrrJasmine** [comment]
@foamliu
I replaced the trimaps generated by the function gen_trimap in util.py by the trimaps DIM author provided, the sad is 66,and the mse is 0.023. I konw the trimap matters to the test results . I am wonder that if I want to compare the result with DIM, I should use the trimaps author provided, right?

**Comment by foamliu** [comment]
@wrrJasmine Thanks, could you share the trimaps DIM author provided? Do you also have the gen_trimap function from the author? If yes we can use that to train the model.

**Comment by wrrJasmine** [comment]
@foamliu Sorry, I do not have the gen_trimap function. The trimaps are in the test folder. You could check it. If you didn't receive it, you could leave your email address and I could send it to you.

**Comment by wrrJasmine** [comment]
@foamliu  https://github.com/poppinace/indexnet_matting/issues/1  the author of Indexnet mentioned how to generate trimaps. But I still don't know how to get it. If you have any idea about it. Please inform me. Thank you again!

**Comment by foamliu** [comment]
@wrrJasmine Thanks a lot, I found the trimaps in the test folder. So I've updated the results table, and will change the test code to use these trimaps later on. Please feel free to push a PR for the test code change if you've time. :)

**Comment by wrrJasmine** [comment]
@foamliu  I have push a PR about the test code change and in order to read the trimap from folder much more convenient , I changed the name of test images compoisited by the code in Combined_Dataset/Test_set/Composition_code_revised.py

**Comment by foamliu** [comment]
@wrrJasmine Thanks a lot, :).

**Comment by wrrJasmine** [comment]
@foamliu 
hi!
I found that one of the trimap in my test forder is much more different from the other 19 trimaps. the name is "girl-1467820_1280_12.png". It is all gray. I am not sure if it is my fault to mix it. would you mind to check it in your test folder?

**Comment by zhzxlcc** [comment]
@wrrJasmine , my trimap--girl-1467820_1280_12.png is the same as your description。

**Comment by Jar7** [comment]
> @foamliu Sorry, I do not have the gen_trimap function. The trimaps are in the test folder. You could check it. If you didn't receive it, you could leave your email address and I could send it to you.

Hello, Could you send me the link to download the dataset, please. my email is ilovece23@gmail.com.

**Comment by wqs111000** [comment]
> @foamliu Sorry, I do not have the gen_trimap function. The trimaps are in the test folder. You could check it. If you didn't receive it, you could leave your email address and I could send it to you.
> Hello, Could you send me the link to download the dataset, please. my email is [ilovece23@gmail.com](mailto:ilovece23@gmail.com).

I emailed the author but haven't gotten a reply yet. Could you share the dataset that DIM author provided? My email is wqs_zju@163.com.
